spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:file:./lokalsi
    username: lokalsi
    password: lokalsi
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  data:
    jpa:
      repositories:
        enabled: true

server:
  contextPath: /api
flyway:
  locations:
    - classpath:/db/migration

