spring:
  datasource:
    url: jdbc:h2:./zrobmywwaw
    username: zrobmywwaw
    password: zrobmywwaw
    driverClassName: org.h2.Driver
  data:
    jpa:
      repositories:
        enabled: true

flyway:
  locations:
    - classpath:/db/migration



